# Generated by Django 5.0.4 on 2024-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('delivery_method', models.CharField(blank=True, max_length=100)),
                ('delivery_method_list', models.TextField(blank=True)),
                ('timeline', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('faq_list', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KnowMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Agile and Scrum', 'Agile and Scrum'), ('Big Data', 'Big Data'), ('Cloud Computing', 'Cloud Computing'), ('Cyber Security', 'Cyber Security'), ('DevOps', 'DevOps'), ('Digital Marketing', 'Digital Marketing'), ('Health and Safety', 'Health and Safety'), ('ISO Certification', 'ISO Certification'), ('IT Services Management', 'IT Services Management'), ('Project Management', 'Project Management'), ('Quality Management', 'Quality Management'), ('UX And Design Thinking', 'UX And Design Thinking')], max_length=50)),
                ('heading1', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description1', models.TextField(blank=True)),
                ('certification_steps', models.ManyToManyField(blank=True, to='base.certificationstep')),
                ('delivery_methods', models.ManyToManyField(blank=True, to='base.deliverymethod')),
                ('faqs', models.ManyToManyField(blank=True, to='base.faq')),
                ('know_mores', models.ManyToManyField(blank=True, to='base.knowmore')),
                ('resources', models.ManyToManyField(blank=True, to='base.resource')),
            ],
        ),
    ]
