# Generated by Django 5.0.4 on 2024-04-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certificationoverview_course_certification_overviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, to='base.learningoutcome'),
        ),
    ]
